name: trigger mobiel tests

on:
  push:
    branches:
      - main
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger workflow in lacoste mobile test
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PAT }}
          repository: ARIDHI/lacoste-mobile-app
          event-type: trigger-tests
          client-payload: '{"tags":"@UAT"}'
